### ISSUE TITLE
Problem using DjangoCMS CKEditor plugin with a CDN like CloudFront

### ISSUE THREAD

**Issue by sampaccoud** [django-cms/djangocms-text-ckeditor#507]
I'm hosting static files on the CloudFront CDN using [django-storages](https://github.com/jschneier/django-storages).

When the CKEditor plugin window opens, I get a 404 on the 3 following files as shown on the attached screenshot:

- djangocms_text_ckeditor/ckeditor/config.js
- djangocms_text_ckeditor/ckeditor/skins/moono-lisa/editor_gecko.css
- djangocms_text_ckeditor/ckeditor/lang/fr.js

A a result, the CKEditor fails to display as seen on the screenshot.

The reason is that CKEditor tries to fetch these 3 files from the main domain, and not from the CDN domain.

Note that CKEditor fetches all the other files from the CDN domain but only these 3 files from the main domain.

My understanding is that these 3 files are called by the javascript itself which seems to build an absolute url for them!? I did not find a way to configure this.

The code responsible for calling these files, as injected in the <head> section of the page:
```html
<head>
    ...
    <script type="text/javascript" src="https://dz0xxxxxxtsm.cloudfront.net/static/djangocms_text_ckeditor/js/dist/bundle-45a646fecc.cms.ckeditor.min.45a646fecced.js"></script>
    ...
    <script type="text/javascript" src="https://nexxxoc.fr/static/djangocms_text_ckeditor/ckeditor/config.js?t=H8DA"></script>
    <link rel="stylesheet" type="text/css" href="https://nexxxoc.fr/static/djangocms_text_ckeditor/ckeditor/skins/moono-lisa/editor_gecko.css?t=H8DA">
    <script type="text/javascript" src="https://nexxxoc.fr/static/djangocms_text_ckeditor/ckeditor/lang/fr.js?t=H8DA"></script>
</head>
```
### Screenshot

![Screenshot from 2019-08-31 08-57-25](https://user-images.githubusercontent.com/1427165/64060636-02ac6780-cbd0-11e9-882e-7c0236c253aa.png)

**Comment by FinalAngel** [comment]
@sampaccoud we're using CloudFlare as a CDN and everything works fine there. From your screenshot I see that some files are correctly served through it (except for the 3 shown)

Is the bundle not served?

https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/widgets.py#L19

**Comment by arnav13081994** [comment]
I was facing the same issue. This is a problem with the library since it uses urljoin to create "TEXT_CKEDITOR_BASE_PATH" (https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/settings.py#L35) and when you are using a CDN, the url so constructed is incorrect because the 'netloc' parameter used by urljoin would be that of your localhost or the domain (as the case maybe) but not of the CDN, if I understand your issue correctly. 

https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/settings.py#L35

I fixed mine by overriding 'TEXT_CKEDITOR_BASE_PATH' in my settings.py by providing the correct url to all static files.

TEXT_CKEDITOR_BASE_PATH = 'https://{}/djangocms_text_ckeditor/ckeditor/'.format(STATIC_URL)

**Comment by sampaccoud** [comment]
Correct! I came to the same solution and was testing it before reporting it.

Random thoughts on how the plugin could be improved:
- document how to make the plugin work with a CDN,
- should the default be computed using the `static` function? Something like:
    ```python
   static('djangocms_text_ckeditor/ckeditor/')
    ```
    instead of 
    ```python
    urljoin(settings.STATIC_URL, 'djangocms_text_ckeditor/ckeditor/')
    ``` 
- apply `TEXT_CKEDITOR_BASE_PATH` to all files and not just those 3 because as explained above some files were called correctly and others not.

**Comment by FinalAngel** [comment]
We welcome any PR @sampaccoud or @arnav13081994 that would improve the CDN implementation. 💯

**Comment by arnav13081994** [comment]
@sampaccoud Firstly the current implementation would work as long as a different webserver or a CDN is not being used to serve static assets.

I don't think using the static function would be a good idea since it will only work when [DEBUG = True](https://github.com/django/django/blob/master/django/conf/urls/static.py#L12).

In my opinion, the easiest solution for now would be to add a line regarding using a CDN for serving static assets.

An implementation solution that would work regardless of DEBUG = true or false and whether the static files are being served by Django or an independent server (or a CDN) would probably involve checking to see if "STATICFILES_STORAGE" is using the default "FileSystemStorage" or not. If it isn't, then "TEXT_CKEDITOR_BASE_PATH" can be overridden like this

```

AWS_LOCATION='static'

AWS_S3_CUSTOM_DOMAIN=[DOMAIN or SUB_DOMAIN_NAME] Eg: static.django.com. 

STATIC_URL = '{}/{}/'.format(AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)

TEXT_CKEDITOR_BASE_PATH = 'https://{}djangocms_text_ckeditor/ckeditor/'.format(STATIC_URL)

```

What do you think? I couldn't think of an easier solution. The main rationale being that "collectstatic" command knows the destination of static files which led me to this.
**Please note this solution assumes static assets in production would be SSL protected.**

**Comment by sampaccoud** [comment]
@arnav13081994 but the static function is used throughout Django to compute static files location (for example here https://github.com/divio/djangocms-text-ckeditor/blob/3a555618d01ebcd3cb65cc238b755a1736e695cb/djangocms_text_ckeditor/widgets.py#L68) so I think it should work?

**Comment by arnav13081994** [comment]
@sampaccoud  Yes you are correct but this is the static template tag. It is being imported from ["django.contrib.admin.templatetags.admin_static " ](https://github.com/divio/djangocms-text-ckeditor/blob/3a555618d01ebcd3cb65cc238b755a1736e695cb/djangocms_text_ckeditor/widgets.py#L7)and weirdly enough if you go to that location there isn't anything like that!

 I think it defaults to using "[from django.templatetags import static](https://github.com/django/django/blob/master/django/templatetags/static.py)". 


Looking at the code it seems that just calling `static(path)` as you had suggested should work perfectly! 


With that being said, I am not sure if this would work because it is supposed to be a template tag and I have never used a template tag well outside a template haha.

**Comment by sampaccoud** [comment]
@arnav13081994 I often use Django's templatetag function directly and think it's ok. I found at least one place in Django's code base where they do that for the `static` function: https://github.com/django/django/blob/26d16c07fdc4a297daca554afa6375c70d6d82a9/django/forms/widgets.py#L107

**Comment by arnav13081994** [comment]
Thank you for the link. Looks like static(path) would work but when I tried to use static, I was getting apps not loaded issue. How did you fix that?

**Comment by sampaccoud** [comment]
This happens if you try to use `static` in your settings file because it comes with the contrib/static app that must first be loaded... 

If you change it in [this file](https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/settings.py#L35) it will work:

```diff
TEXT_CKEDITOR_BASE_PATH = getattr(
-    settings, 'TEXT_CKEDITOR_BASE_PATH', urljoin(settings.STATIC_URL, 'djangocms_text_ckeditor/ckeditor/')
+    settings, 'TEXT_CKEDITOR_BASE_PATH', static('djangocms_text_ckeditor/ckeditor/')
)
```

**Comment by arnav13081994** [comment]
I see. Makes sense. Thanks!

@FinalAngel Should a fix be pushed for this issue?
