### ISSUE TITLE
Impossible to override allowed_css_properties of TextSanitizer

### ISSUE THREAD

**Issue by gs1-rob-392** [django-cms/djangocms-text-ckeditor#643]
Hi, is there a way to override _allowed_css_properties_ of TextSanitizer?
I'm trying to add **box-shadow**, because _html5lib.Filter_ doesn't include it.

**Comment by fsbraun** [comment]
Hi @gs1-rob-392 ! Indeed, this is not easily possible with a setting. Since the sanitizer of Html5lib has been deprecated (#632)  I do not expect changes to the current sanitizing process but rather an update to another sanitizer library.

If you need this urgently, I'd suggest patching `djangocms_text_ckeditor.html._filter_kwargs()` function to include the `allowed_css_properties` you need. Not nice, but a work-around.
